# Generated by Django 5.1.6 on 2025-02-10 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organazation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='title')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='token')),
            ],
            options={
                'verbose_name': 'Organazation',
                'verbose_name_plural': 'Organazations',
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_types', to='corparation.organazation')),
            ],
            options={
                'verbose_name': 'Food Type',
                'verbose_name_plural': 'Food Types',
            },
        ),
        migrations.CreateModel(
            name='CarsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_types', to='corparation.organazation')),
            ],
            options={
                'verbose_name': 'Car Type',
                'verbose_name_plural': 'Car Types',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=280, unique=True, verbose_name='address')),
                ('latidute', models.FloatField(verbose_name='latidute')),
                ('longitude', models.FloatField(verbose_name='longtitude')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corparation.organazation', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='OtherProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_product_types', to='corparation.organazation')),
            ],
            options={
                'verbose_name': 'Other Product Type',
                'verbose_name_plural': 'Other Product Types',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corparation.organazation', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
    ]
