# Generated by Django 5.1.6 on 2025-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corparation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='latidute',
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
